In [202]:
import pandas as pd
import numpy as np

In [203]:
customers = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 105, 106, 106, 107, np.nan],
    "Full_Name": [
        "  Alice Smith",
        "BOB jones ",
        "charlie BROWN",
        "david white",
        "  Eva Green",
        "Freya Clarke",
        "Freya Clarke",
        "  grace O'neil ",
        "henry adams"
    ],
    "Email": [
        "ALICE@EXAMPLE.COM",
        "bob@example.com ",
        None,
        "DAVID@EXAMPLE.COM",
        "eva@example.com",
        "freya@example.com",
        "freya@example.com",
        "grace@example.com",
        "HENRY@EXAMPLE.COM"
    ],
    "City": [
        " london",
        "Manchester ",
        "LEEDS",
        "London",
        "manchester",
        "Bristol",
        "Bristol",
        "London",
        "Manchester"
    ],
    "Signup_Date": [
        "2023-01-15",
        "15/02/2023",
        "2023-03-05",
        "2023/04/10",
        "2023-05-20",
        "2023-06-11",
        "2023-06-11",
        "2023-07-01",
        "2023-08-12"
    ],
    "Age": [
        "32",
        "41",
        "29",
        None,
        "35",
        "27",
        "27",
        "44",
        "38"
    ],
    "Plan_Type": [
        "basic",
        "Premium",
        "BASIC",
        "premium",
        "Basic",
        "standard",
        "Standard",
        "Premium",
        "basic"
    ]
})

In [204]:
customers['Full_Name'] = customers['Full_Name'].str.strip()

customers.Full_Name

0      Alice Smith
1        BOB jones
2    charlie BROWN
3      david white
4        Eva Green
5     Freya Clarke
6     Freya Clarke
7     grace O'neil
8      henry adams
Name: Full_Name, dtype: object

In [205]:
customers['Email'] = customers['Email'].str.strip().str.lower()

In [206]:
customers["Full_Name"] = customers["Full_Name"].str.strip().str.title()

In [207]:
customers["City"] = customers["City"].str.strip().str.title()

In [208]:
customers['Full_Name'] = (
    customers['Full_Name']
    .str.strip()
    .str.replace(r'\s+', " ", regex=True)
    .str.title()
)

In [209]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  8 non-null      float64
 1   Full_Name    9 non-null      object
 2   Email        8 non-null      object
 3   City         9 non-null      object
 4   Signup_Date  9 non-null      object
 5   Age          8 non-null      object
 6   Plan_Type    9 non-null      object
dtypes: float64(1), object(6)
memory usage: 636.0+ bytes

In [210]:
customers.dtypes[customers.dtypes == 'object'].index

Index(['Full_Name', 'Email', 'City', 'Signup_Date', 'Age', 'Plan_Type'], dtype='object')

In [211]:
customers['Plan_Type'] = (
    customers['Plan_Type']
    .str.strip()
    .str.lower()
    .str.capitalize()
)

In [212]:
customers

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type
0,101.0,Alice Smith,alice@example.com,London,2023-01-15,32,Basic
1,102.0,Bob Jones,bob@example.com,Manchester,15/02/2023,41,Premium
2,103.0,Charlie Brown,None,Leeds,2023-03-05,29,Basic
3,104.0,David White,david@example.com,London,2023/04/10,None,Premium
4,105.0,Eva Green,eva@example.com,Manchester,2023-05-20,35,Basic
5,106.0,Freya Clarke,freya@example.com,Bristol,2023-06-11,27,Standard
6,106.0,Freya Clarke,freya@example.com,Bristol,2023-06-11,27,Standard
7,107.0,Grace O'Neil,grace@example.com,London,2023-07-01,44,Premium
8,NaN,Henry Adams,henry@example.com,Manchester,2023-08-12,38,Basic

In [213]:
customers['Age'] = pd.to_numeric(customers['Age'], errors='coerce')

customers

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type
0,101.0,Alice Smith,alice@example.com,London,2023-01-15,32.0,Basic
1,102.0,Bob Jones,bob@example.com,Manchester,15/02/2023,41.0,Premium
2,103.0,Charlie Brown,None,Leeds,2023-03-05,29.0,Basic
3,104.0,David White,david@example.com,London,2023/04/10,NaN,Premium
4,105.0,Eva Green,eva@example.com,Manchester,2023-05-20,35.0,Basic
5,106.0,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard
6,106.0,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard
7,107.0,Grace O'Neil,grace@example.com,London,2023-07-01,44.0,Premium
8,NaN,Henry Adams,henry@example.com,Manchester,2023-08-12,38.0,Basic

In [214]:
customers["Customer_ID"] = pd.to_numeric(
    customers["Customer_ID"],
    errors="coerce"
).astype("Int64")

In [215]:
customers['Signup_Date'] = pd.to_datetime(
    customers['Signup_Date'],
    errors='coerce',
    format="%Y-%m-%d",
)

customers

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type
0,101,Alice Smith,alice@example.com,London,2023-01-15,32.0,Basic
1,102,Bob Jones,bob@example.com,Manchester,NaT,41.0,Premium
2,103,Charlie Brown,None,Leeds,2023-03-05,29.0,Basic
3,104,David White,david@example.com,London,NaT,NaN,Premium
4,105,Eva Green,eva@example.com,Manchester,2023-05-20,35.0,Basic
5,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard
6,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard
7,107,Grace O'Neil,grace@example.com,London,2023-07-01,44.0,Premium
8,<NA>,Henry Adams,henry@example.com,Manchester,2023-08-12,38.0,Basic

In [216]:
customers['Signup_Date'].dtype

dtype('<M8[ns]')

In [217]:
customers["Signup_Year"] = customers["Signup_Date"].dt.year
customers["Signup_Month"] = customers["Signup_Date"].dt.month
customers["Signup_Day"] = customers["Signup_Date"].dt.day

In [218]:
customers

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type,Signup_Year,Signup_Month,Signup_Day
0,101,Alice Smith,alice@example.com,London,2023-01-15,32.0,Basic,2023.0,1.0,15.0
1,102,Bob Jones,bob@example.com,Manchester,NaT,41.0,Premium,NaN,NaN,NaN
2,103,Charlie Brown,None,Leeds,2023-03-05,29.0,Basic,2023.0,3.0,5.0
3,104,David White,david@example.com,London,NaT,NaN,Premium,NaN,NaN,NaN
4,105,Eva Green,eva@example.com,Manchester,2023-05-20,35.0,Basic,2023.0,5.0,20.0
5,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0
6,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0
7,107,Grace O'Neil,grace@example.com,London,2023-07-01,44.0,Premium,2023.0,7.0,1.0
8,<NA>,Henry Adams,henry@example.com,Manchester,2023-08-12,38.0,Basic,2023.0,8.0,12.0

In [219]:
customers["Signup_Month_Name"] = customers["Signup_Date"].dt.month_name()

In [220]:
customers

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type,Signup_Year,Signup_Month,Signup_Day,Signup_Month_Name
0,101,Alice Smith,alice@example.com,London,2023-01-15,32.0,Basic,2023.0,1.0,15.0,January
1,102,Bob Jones,bob@example.com,Manchester,NaT,41.0,Premium,NaN,NaN,NaN,NaN
2,103,Charlie Brown,None,Leeds,2023-03-05,29.0,Basic,2023.0,3.0,5.0,March
3,104,David White,david@example.com,London,NaT,NaN,Premium,NaN,NaN,NaN,NaN
4,105,Eva Green,eva@example.com,Manchester,2023-05-20,35.0,Basic,2023.0,5.0,20.0,May
5,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0,June
6,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0,June
7,107,Grace O'Neil,grace@example.com,London,2023-07-01,44.0,Premium,2023.0,7.0,1.0,July
8,<NA>,Henry Adams,henry@example.com,Manchester,2023-08-12,38.0,Basic,2023.0,8.0,12.0,August

In [221]:
customers[customers.duplicated()]

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type,Signup_Year,Signup_Month,Signup_Day,Signup_Month_Name
6,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0,June

In [222]:
customers.duplicated().sum()

np.int64(1)

In [223]:
customers[customers.duplicated(subset=['Email'], keep=False)]

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type,Signup_Year,Signup_Month,Signup_Day,Signup_Month_Name
5,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0,June
6,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0,June

In [224]:
customers = customers.drop_duplicates(subset=["Email"], keep="first")

In [225]:
customers["Plan_Type"] = customers["Plan_Type"].astype("category")
customers["City"] = customers["City"].astype("category")

C:\Users\Samuel\AppData\Local\Temp\ipykernel_10404\346812964.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers["Plan_Type"] = customers["Plan_Type"].astype("category")
C:\Users\Samuel\AppData\Local\Temp\ipykernel_10404\346812964.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers["City"] = customers["City"].astype("category")

In [226]:
customers["Age_Group"] = pd.cut(
    customers["Age"],
    bins=[0, 17, 30, 45, 120],
    labels=["Under 18", "18-30", "31-45", "46+"]
)

C:\Users\Samuel\AppData\Local\Temp\ipykernel_10404\452228237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers["Age_Group"] = pd.cut(

In [227]:
customers

,Customer_ID,Full_Name,Email,City,Signup_Date,Age,Plan_Type,Signup_Year,Signup_Month,Signup_Day,Signup_Month_Name,Age_Group
0,101,Alice Smith,alice@example.com,London,2023-01-15,32.0,Basic,2023.0,1.0,15.0,January,31-45
1,102,Bob Jones,bob@example.com,Manchester,NaT,41.0,Premium,NaN,NaN,NaN,NaN,31-45
2,103,Charlie Brown,None,Leeds,2023-03-05,29.0,Basic,2023.0,3.0,5.0,March,18-30
3,104,David White,david@example.com,London,NaT,NaN,Premium,NaN,NaN,NaN,NaN,NaN
4,105,Eva Green,eva@example.com,Manchester,2023-05-20,35.0,Basic,2023.0,5.0,20.0,May,31-45
5,106,Freya Clarke,freya@example.com,Bristol,2023-06-11,27.0,Standard,2023.0,6.0,11.0,June,18-30
7,107,Grace O'Neil,grace@example.com,London,2023-07-01,44.0,Premium,2023.0,7.0,1.0,July,31-45
8,<NA>,Henry Adams,henry@example.com,Manchester,2023-08-12,38.0,Basic,2023.0,8.0,12.0,August,31-45