In [2]:
import numpy as np
import pandas as pd

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [5]:
df = pd.DataFrame(data, columns=columns)

In [8]:
df[['Make', 'Model', 'MSRP']].shape

(5, 3)

In [9]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [11]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [13]:
df.loc[['a', 'c', 'e'], ['Make', 'Model', 'MSRP']]

     Make     Model   MSRP
a  Nissan    Stanza   2000
c   Lotus     Elise  54990
e  Nissan  Frontier  32340

In [14]:
df.iloc[[0,1,3]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [17]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] > 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [18]:
df['Vehicle_Style'].value_counts()

Vehicle_Style
sedan          1
Sedan          1
convertible    1
4dr SUV        1
Pickup         1
Name: count, dtype: int64

In [19]:
df['Vehicle_Style'].str.lower()

a          sedan
b          sedan
c    convertible
d        4dr suv
e         pickup
Name: Vehicle_Style, dtype: object

In [21]:
df.MSRP.describe().round()

count        5.0
mean     30186.0
std      18985.0
min       2000.0
25%      27150.0
50%      32340.0
75%      34450.0
max      54990.0
Name: MSRP, dtype: float64

In [22]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               5 non-null      object
 1   Model              5 non-null      object
 2   Year               5 non-null      int64
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64
 5   Transmission Type  5 non-null      object
 6   Vehicle_Style      5 non-null      object
 7   MSRP               5 non-null      int64
dtypes: float64(1), int64(3), object(4)
memory usage: 532.0+ bytes

In [24]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [25]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])